## Numpy Libraries:
  - Very fast and Fundamental library for scientific mathematical computing
  - provide support for the array and matrices, along with the collection of mathematical function to operate on these data structures.

### Lets see the basics of numpy, focussing on arrays and vectorized operation. 
  - Create an n-dimensional array ndarray which is the core data structure of this library where all the functions implemented.
  - Install numpy

In [ ]:
import numpy as np # usual convention 

# create an 1d array
# by using an list and tuple to create an array using the array function.
# List and array looks different 
arr = np.array([1,2,3,4,5])
print(arr)
arr1 = np.array((9,8,7,6,5))
print(arr1)

#  to check its type
print(type(arr)) # type ndarray
print(arr.shape) # 1d so it (5, ) -> 1 value in the tuple

# lets reshape the array

arr2 = np.array([3,4,5,6,7,8])
# turning the 1d to 2d -> we can reshape the 1d array into 2d-> possible -> 1,6 or 6,1 , 2,3 or 3,2

arr3 = arr2.reshape(6,1)
#  after this reshape we can find that the shape transformed from (6, ) to (6,1) -> seems 2d it is now
print(arr3)

# we can create 2d by nested lists [[1,2,3,4,5,6][3,4,5,6,7,8]] [[row1 elements][column elements]]
arr_2d = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr_2d)
# array attributes
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.itemsize)
print(arr_2d.nbytes)
print(arr_2d.size)
print(arr_2d.dtype)
# we can create an 3d array as well literally by nested list or tuple

arr_3d = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[7,8,9]]])
print(arr_3d)
print(type(arr_3d))
print(arr_3d.shape)
print(arr_3d.ndim)
print(arr_3d.itemsize)
print(arr_3d.nbytes)
print(arr_3d.size)
print(arr_3d.dtype)

# transforming the 1d array to 2d and 3d

arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr1.copy().reshape(3,4)
arr3 = arr1.copy().reshape(2,2,3)
print(arr2)
print(arr3)

In [ ]:
# lets create an array using the in-built function 

# np.arange(range) -> return an array with the range we mentioned 
arr1 = np.arange(1,13).reshape(2,6)
print(arr1)

# empty array we can define 
arr_empty = np.empty((2,3))
print(arr_empty) 

# zero array 
arr_zero = np.zeros((4,4))
print(arr_zero)

# ones -> ones array

arr_ones = np.ones((2,3,4))
print(arr_ones)

# Identity Matrix -> is a square and all the diagonal elements are 1 and others are zero
identity = np.eye(3,3)
print(identity)



In [30]:
# Numpy vectorized operation 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

# Element wie addition arr1 + arr2 -> all operation apply on the element wise -> addition, subtraction and multiply 
# and division and floor division and modulus 
print("Addition : ", arr1 + arr2)
print("subtraction : ", arr1 - arr2)
print("Multiplication  : ", arr1 * arr2)
print("division : ", arr1 / arr2)
print("modulus : ", arr1 % arr2)
print("floor division : ", arr1// arr2)
print("Exponentiation: ", arr1 ** arr2)

# Universal Functions:
sample = np.arange(1,13).reshape(4,3)

# square root
sq_rt = np.sqrt(sample)
print(sq_rt)

# Square
square = np.square(sample)
print(square)

# Exponential 
exp = np.exp(sample)
print(exp)

# sine => we can do all trigonometric angles and hyperbolic function values for all the element -> element wise o/p
sine_value = np.sin(sample)
print(sine_value)
# logarithmic 
# log_value with base 10 
log_val = np.log10(sample)
print(log_val)

# natural log
log_val = np.log(sample)
print(log_val)


Addition :  [ 5  7  9 11 13 15]
subtraction :  [-3 -3 -3 -3 -3 -3]
Multiplication  :  [ 4 10 18 28 40 54]
division :  [0.25       0.4        0.5        0.57142857 0.625      0.66666667]
modulus :  [1 2 3 4 5 6]
floor division :  [0 0 0 0 0 0]
Exponentiation:  [       1       32      729    16384   390625 10077696]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]
 [1.         1.04139

In [ ]:
# Array slicing and Indexing

# slicing the array with slice object 
arr = np.arange(12).reshape(3,4)
print(arr)

# slicing the single element in the array
# by using the elemnt index value of the element 

print(arr[0][1])

# to take the sub-array from the array 
# [from which row to start and end, from which column to start and end ]
print(arr[1:,2:]) 
print(arr[1,1:3])
print(arr[0:2, 2:])

arr_3d = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[7,8,9]]])
print(arr_3d)

# access the single element 
print(arr_3d[1][0][1])

# to access the sub array 
print(arr_3d[0:,0:, 1:])

# to access the sub array 
print(arr_3d[0,0:, 1:])


In [ ]:
# Modify the array elements
arr1 = np.array((9,8,7,6,5))
arr2 = np.arange(6).reshape(2,3)
arr3 = np.arange(12).reshape(2,3,2)

arr1[2] = 5
print(arr2)
arr2[0,0] = 100
print(arr2)
print(arr3)
arr3[1,0,1] = 20
print(arr3)

# we can change the multiple values

arr2[1:,1:] = 88
print(arr2)


In [73]:
# Statistical Concepts:
sample_arr = np.arange(1,9)
print("sample arr" , sample_arr)

#  mean of an array
mean = np.mean(sample_arr)
print("mean", mean)

# Median of an array 
median = np.median(sample_arr)
print("median", median)

# std.deviation of an array
std_dev = np.std(sample_arr)
print("std dev:", std_dev)

# Variance
variance = np.var(sample_arr)
print("variance", variance)

sample arr [1 2 3 4 5 6 7 8]
mean 4.5
median 4.5
std dev: 2.29128784747792
variance 5.25


In [72]:

# Normalization: normalize the data, so that we can have a the mean as zero and std deviation as 1 
# To normalize the array: 

# for 1d array 
arr1 =np.arange(5)

# mean and standard deviation for the 1d array 
mean = np.mean(arr1) # it gives the mean of the matrix
std_dev = np.std(arr1) # it gives th std deviation 

#  to normalize the data 
normalized_data = (arr1 - mean)/ std_dev

print("Normalized data 1d: " , normalized_data)

# for 2d array 
arr2 =np.arange(9).reshape(3,3)

# mean and standard deviation for the 1d array 
mean = np.mean(arr2) # it gives the mean of the matrix
std_dev = np.std(arr2) # it gives th std deviation 

#  to normalize the data 
normalized_data = (arr2 - mean)/ std_dev

print("Normalized data for 2d 3x3 matrix: " , normalized_data)

# for 3d array 
arr3 =np.arange(12).reshape(2,2,3)

# mean and standard deviation for the 1d array 
mean = np.mean(arr3) # it gives the mean of the matrix
std_dev = np.std(arr3) # it gives th std deviation 

#  to normalize the data 
normalized_data = (arr3 - mean)/ std_dev

print("Normalized data for 3d 2*2*3 matrix: " , normalized_data)

Normalized data 1d:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Normalized data for 2d 3x3 matrix:  [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
Normalized data for 3d 2*2*3 matrix:  [[[-1.59325501 -1.30357228 -1.01388955]
  [-0.72420682 -0.43452409 -0.14484136]]

 [[ 0.14484136  0.43452409  0.72420682]
  [ 1.01388955  1.30357228  1.59325501]]]


In [ ]:
# Logical operation 
data = np.arange(9)
print(data)
print(data[(data>=5) & (data<8)])
# This is super important while we go further into the pandas library 
# when we do data analysis, we will have an excel sheet or csv files to work on, which has the data frame.
# In the data frame, we can specifically apply this logical operation within the array itself.
# we can write any condition like  (data>=5) or data%2 == 0 or data&1 == 1 
# we can do multiple condition such as & operator or | or logical operator. 


[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


: 